export const ordTemplate = '[Link] \n' +
'PocketPCPath="" \n' +
'PCPath="C:\Users\kael\Desktop\Job.cvj" \n' +
'PCDate="3940100272-30995418" \n' +
'CreateBy="PC_CV" \n' +
' \n' +
'[Header] \n' +
'Version=4 \n' +
'Unit=0 \n' +
'Name="Job" \n' +
'Description="Default" \n' +
'PurchaseOrder="" \n' +
'Comment="" \n' +
'Customer="" \n' +
'Contact="" \n' +
'Address1="" \n' +
'Address2="" \n' +
'City="" \n' +
'State="" \n' +
'Zip="" \n' +
'Phone="" \n' +
'Fax="" \n' +
'Mobile="" \n' +
'EMail="" \n' +
'ShipToComment="" \n' +
'ShipToCustomer="" \n' +
'ShipToContact="" \n' +
'ShipToAddress1="" \n' +
'ShipToAddress2="" \n' +
'ShipToCity="" \n' +
'ShipToState="" \n' +
'ShipToZip="" \n' +
'ShipToPhone="" \n' +
'ShipToFax="" \n' +
'ShipToMobile="" \n' +
'ShipToEMail="" \n' +
'BaseDoors="East Coast 12","MDF - Spray MB","","","","EastCoast","TLD DOORS","" \n' +
'WallDoors="East Coast 12","MDF - Spray MB","","","","EastCoast","TLD DOORS","" \n' +
'DrawerFront="East Coast 12","MDF - Spray MB","","","","EastCoast","TLD DOORS","" \n' +
'BaseEndPanels="MDF - Spray","MDF - Spray 3/4","","","","EastCoast","TLD DOORS","" \n' +
'WallEndPanels="MDF - Spray","MDF - Spray 3/4","","","","EastCoast","TLD DOORS","" \n' +
'TallEndPanels="MDF - Spray","MDF - Spray 3/4","","","","EastCoast","TLD DOORS","" \n' +
'CabinetConstruction="Kitchen by true" \n' +
'DrawerBoxConstruction="Vionaro System Drawer" \n' +
'RollOutConstruction="N/A" \n' +
'BaseCabinetMaterials="EXTERIOR-Mdf / INTERIOR-True white mel" \n' +
'WallCabinetMaterials="EXTERIOR-Mdf / INTERIOR-True white mel" \n' +
'BaseExposedCabinetMaterials="MDF" \n' +
'WallExposedCabinetMaterials="MDF" \n' +
'DrawerBoxMaterials="5/8 White Mel" \n' +
'RollOutMaterials="N/A" \n' +
'PullMaterials="Designer pull" \n' +
'HingeMaterials="Grass soft close full over overlay" \n' +
'GuideMaterials="Grass Vionaro Box" \n' +
'ClosetBaseDoors="Slab Vertical Grain","Tafisa 1","","","","","TLD DOORS","" \n' +
'ClosetWallDoors="Slab Vertical Grain","Tafisa 1","","","","","TLD DOORS","" \n' +
'ClosetDrawerFront="Slab Horizontal Grain","Tafisa 1","","","","","TLD DOORS","" \n' +
'ClosetBaseEndPanels="N/A","N/A","","","","","TLD DOORS","" \n' +
'ClosetWallEndPanels="N/A","N/A","","","","","TLD DOORS","" \n' +
'ClosetTallEndPanels="N/A","N/A","","","","","TLD DOORS","" \n' +
'ClosetCabinetConstruction="1 Essentials " \n' +
'ClosetDrawerBoxConstruction="Lifestile Box" \n' +
'ClosetRollOutConstruction="N/A" \n' +
'ClosetMaterials="True White MEL" \n' +
'ClosetDrawerBoxMaterials="5/8 White Mel" \n' +
'ClosetRollOutMaterials="N/A" \n' +
'ClosetPullMaterials="Designer pull" \n' +
'ClosetGuideMaterials="Lifestile Box 16mm" \n' +
'ClosetWireBasketMaterials="N/A" \n' +
'ClosetRodMaterials="TRUE-Oval Chrome" \n' +
'ClosetHingeMaterials="Grass soft close full over overlay" \n' +
'InteriorFinish="_True White Spray" \n' +
'ExteriorFinish="_True White Spray" \n' +
' \n' +
'[[:: Walls ::]]' + 
'[[:: Catalog ::]]'